version: '3.8'

services:
  # Backend Service (Flask API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: omniful-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=asdf#FGSgvasgf$5$WGT
      - PYTHONUNBUFFERED=1
    volumes:
      - backend-data:/app/src/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:5000/api/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - omniful-network

  # Frontend Service (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: omniful-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - omniful-network

volumes:
  backend-data:
    driver: local

networks:
  omniful-network:
    driver: bridge

